package com.github.mraa4j.enums;



public enum ResultT {
	MRAA_SUCCESS,
	MRAA_ERROR_FEATURE_NOT_IMPLEMENTED,
	MRAA_ERROR_FEATURE_NOT_SUPPORTED,
	MRAA_ERROR_INVALID_VERBOSITY_LEVEL,
	MRAA_ERROR_INVALID_PARAMETER,
	MRAA_ERROR_INVALID_HANDLE,
	MRAA_ERROR_NO_RESOURCES,
	MRAA_ERROR_INVALID_RESOURCE,
	MRAA_ERROR_INVALID_QUEUE_TYPE,
	MRAA_ERROR_NO_DATA_AVAILABLE,
	MRAA_ERROR_INVALID_PLATFORM,
	MRAA_ERROR_PLATFORM_NOT_INITIALISED,
	MRAA_ERROR_PLATFORM_ALREADY_INITIALISED,
	MRAA_ERROR_UNSPECIFIED;


	static public ResultT fromValue(int v) {
		return Helper.fromValue(ResultT.class, v);
	}

}
